#!/usr/bin/env sh
set -e

echo "fmt check"
cargo fmt --check
echo "clippy"
echo "| default   feature"
cargo clippy -q -- -D warnings
echo "| anyhow    feature "
cargo clippy -q --no-default-features --features anyhow -- -D warnings
echo "| report    feature "
cargo clippy -q --no-default-features --features report -- -D warnings
echo "| error     feature "
cargo clippy -q --no-default-features --features error -- -D warnings
echo "| cli-error feature "
cargo clippy -q --no-default-features --features cli-error -- -D warnings
echo "build tests"
cargo test -q --no-run
echo "run tests"
cargo test -q
